import {Component,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {RouterLink} from '@angular/router';
import {ApiService} from '../core/api.service';
import {money} from '../core/models';
@Component({standalone:true,imports:[FormsModule,RouterLink],template:`<div class="page"><div class="page-heading"><div class="eyebrow">KNIGHTCORE OPERATIONS</div><h1>Admin workspace</h1><p>Manage projects, prepare custom offers, and maintain the collection.</p></div>@if(error()){<div class="alert error">{{error()}}</div>}@if(message()){<div class="alert success">{{message()}}</div>}<div class="admin-stats">@for(s of stats();track s.label){<div class="panel"><strong>{{s.value}}</strong><p>{{s.label}}</p></div>}</div><div class="workspace-tabs">@for(t of tabs;track t){<button [class.active]="tab()===t" (click)="tab.set(t)">{{t}}</button>}</div>
@if(tab()==='Orders'){<div class="order-grid">@for(o of orders();track o.id){<a class="order-card" [routerLink]="['/orders',o.id]"><div class="row-between"><strong>{{o.number}}</strong><span class="status-badge">{{o.status}}</span></div><h3>{{o.snapshot.packageName}}</h3><p>{{o.name}} · {{o.email}}</p><div class="order-card-bottom"><strong>{{money(o.snapshot.total)}}</strong><span>Manage project →</span></div></a>}@empty{<div class="panel">No orders yet.</div>}</div>}
@if(tab()==='Requests'){<div class="request-list">@for(r of requests();track r.id){<div class="panel"><div class="row-between"><h3>{{r.packageName}}</h3><span class="status-badge">{{r.status}}</span></div><p>{{r.customerName}} · {{r.email}}</p><p class="preserve-lines">{{r.requirements}}</p><button class="btn secondary" (click)="selectRequest(r)">Prepare offer</button></div>}@empty{<div class="panel">No custom requests yet.</div>}</div>@if(selectedRequest){<div class="panel"><h3>Custom offer</h3><p>Base configuration {{money(selectedRequest.price.subtotal)}}. Add the agreed custom development cost below.</p><label>Agreed scope<textarea [(ngModel)]="scope"></textarea></label><div class="form-grid"><label>Additional price (INR)<input type="number" min="0" [(ngModel)]="customPrice"></label><label>Delivery estimate<input [(ngModel)]="delivery"></label></div><button class="btn" [disabled]="busy()" (click)="offer()">Send offer to customer workspace</button></div>}}
@if(tab()==='Catalog'){<div class="panel"><h2>Publish a package version</h2><p>Existing quotes preserve their agreed prices. Changes apply to new configurations.</p><label>Package<select (change)="selectPackage($any($event.target).value)"><option value="">Choose package</option>@for(p of packages();track p.id){<option [value]="p.id">{{p.name}}</option>}</select></label>@if(packageId){<label>Package configuration (JSON)<textarea class="admin-editor" [(ngModel)]="editor"></textarea></label><button class="btn" [disabled]="busy()" (click)="publish()">Publish new version</button>}</div>}
@if(tab()==='Failed jobs'){<div class="request-list">@for(j of jobs();track j.id){<div class="panel"><h3>{{j.kind}}</h3><p>{{j.lastError}} · {{j.attempts}} attempts</p><button class="btn secondary" [disabled]="busy()" (click)="retry(j.id)">Retry job</button></div>}@empty{<div class="panel">No failed jobs need attention.</div>}</div>}</div>`})
export class AdminComponent{
 private api=inject(ApiService);tabs=['Orders','Requests','Catalog','Failed jobs'];tab=signal('Orders');stats=signal<{label:string,value:number}[]>([]);orders=signal<any[]>([]);requests=signal<any[]>([]);packages=signal<any[]>([]);jobs=signal<any[]>([]);error=signal('');message=signal('');busy=signal(false);money=money;selectedRequest:any=null;scope='';customPrice=0;delivery='';packageId='';editor='';
 constructor(){void this.load()}
 async load(){try{const [s,o,r,c,j]=await Promise.all([this.api.get<any>('admin/overview'),this.api.get<any>('admin/orders'),this.api.get<any[]>('admin/custom-requests'),this.api.get<any>('catalog'),this.api.get<any[]>('admin/jobs')]);this.stats.set(Object.entries(s).map(([label,value])=>({label,value:Number(value)})));this.orders.set(o.items);this.requests.set(r);this.packages.set(c.packages);this.jobs.set(j)}catch(e){this.error.set((e as Error).message)}}
 selectRequest(r:any){this.selectedRequest=r;this.scope=r.requirements;this.delivery='3–4 weeks';this.customPrice=0}
 selectPackage(id:string){this.packageId=id;const p=this.packages().find(x=>x.id===id);if(p)this.editor=JSON.stringify({version:p.version,name:p.name,summary:p.summary,basePrice:Number(p.basePrice),delivery:p.delivery,included:p.included,features:p.features.map((f:any)=>({code:f.code,name:f.name,description:f.description,unitPrice:Number(f.unitPrice),priceMode:f.priceMode,maxQuantity:f.maxQuantity,requires:f.requires}))},null,2)}
 async action(fn:()=>Promise<unknown>,message:string){this.busy.set(true);this.error.set('');this.message.set('');try{await fn();this.message.set(message);await this.load()}catch(e){this.error.set((e as Error).message)}finally{this.busy.set(false)}}
 async offer(){await this.action(()=>this.api.post('admin/custom-requests/'+this.selectedRequest.id+'/offer',{scope:this.scope,customAmount:this.customPrice,delivery:this.delivery,validDays:7}),'Offer is available in the customer workspace.')}
 async publish(){await this.action(()=>this.api.post('admin/packages/'+this.packageId+'/publish',JSON.parse(this.editor)),'New package version published.');this.selectPackage(this.packageId)}
 async retry(id:string){await this.action(()=>this.api.post('admin/jobs/'+id+'/retry',{}),'Retry scheduled.')}
}
