import {Component,inject,signal} from '@angular/core';
import {FormBuilder,ReactiveFormsModule,Validators} from '@angular/forms';
import {ActivatedRoute,Router,RouterLink} from '@angular/router';
import {ApiService} from '../core/api.service';
import {DraftService} from '../core/draft.service';
import {Price,Quote,Billing,money} from '../core/models';
@Component({standalone:true,imports:[ReactiveFormsModule,RouterLink],template:`
<div class="page checkout-page"><a routerLink="/" class="back-link">← Software collection</a><div class="page-heading"><div><div class="eyebrow">YOUR NEXT MOVE</div><h1>{{draft.value()?.custom&&!quote()?'Tell us what you need.':'Review your project.'}}</h1><p>A clear scope. A clear price. Everything in one place.</p></div><span class="step-label">02 / Review</span></div>
@if(error()){<div class="alert error" role="alert">{{error()}}</div>}
@if(success()){<section class="empty-panel"><span class="success-symbol">✓</span><h2>Your request is with us.</h2><p>We’ll review your requirements and send a quote for your approval.</p><a class="btn btn-primary" routerLink="/workspace">Open workspace →</a></section>}
@else if(quote();as q){
<div class="config-layout"><div><section class="panel"><span class="eyebrow">AGREED SCOPE</span><h2>{{q.snapshot.packageName}}</h2><div class="included-grid">@for(f of q.snapshot.included;track f){<div class="included-item"><span class="check-disc">✓</span>{{f}}</div>}</div>@if(q.snapshot.scope){<div class="scope-note"><h3>Custom development</h3><p>{{q.snapshot.scope}}</p></div>}<div class="detail-divider"></div><span class="eyebrow">BILLING DETAILS</span><h3>{{q.snapshot.billing.businessName}}</h3><p class="address">{{q.snapshot.billing.address}}<br>{{q.snapshot.billing.city}}, {{q.snapshot.billing.state}} {{q.snapshot.billing.postalCode}}</p><p class="field-hint">Estimated delivery: {{q.snapshot.delivery}}</p><p class="field-hint">Quote valid until {{expiry(q.expiresUtc)}}</p>@if(q.snapshot.evaluation){<div class="alert info">Evaluation order. The generated document will be marked as a sample invoice.</div>}</section></div><aside class="summary-panel"><span class="eyebrow">ORDER SUMMARY</span><h2>{{q.snapshot.packageName}}</h2><div class="summary-lines">@for(line of q.snapshot.lines;track line.code){<div><span>{{line.name}}@if(line.quantity>1){ × {{line.quantity}}}</span><strong>{{money(line.amount)}}</strong></div>}<div><span>Applicable tax</span><strong>{{money(q.snapshot.taxAmount)}}</strong></div></div><div class="summary-total"><span>Total amount</span><strong>{{money(q.snapshot.total)}}</strong><small>One-time project price</small></div><label class="accept-terms"><input type="checkbox" [checked]="accepted()" (change)="accepted.set($any($event.target).checked)"><span>I accept the scope, delivery estimate, and total in this quote.</span></label><button class="btn btn-primary full-width" (click)="place()" [disabled]="!accepted()||busy()||q.status!=='Offered'">{{busy()?'Confirming…':'Confirm order'}} →</button><p class="summary-footnote">Your invoice will be available in your workspace.</p>@if(draft.value()&&!q.snapshot.scope){<button class="link-button full-width" (click)="edit()">Edit billing details</button>}</aside></div>
}@else if(draft.value();as d){
<div class="config-layout"><section class="panel"><div class="section-heading"><span class="step-circle">01</span><div><h2>Your business details</h2><p>These details will appear on your invoice.</p></div></div><form [formGroup]="form" (ngSubmit)="review()" novalidate><label>Business or billing name<input formControlName="businessName" autocomplete="organization" maxlength="120" placeholder="Your business name"></label><label>Billing address<textarea formControlName="address" rows="2" autocomplete="street-address" maxlength="250" placeholder="Street and building"></textarea></label><div class="form-grid"><label>City<input formControlName="city" autocomplete="address-level2" maxlength="80"></label><label>State<input formControlName="state" autocomplete="address-level1" maxlength="80"></label><label>PIN code<input formControlName="postalCode" autocomplete="postal-code" inputmode="numeric" maxlength="6"></label><label>Tax ID <span class="optional">optional</span><input formControlName="taxId" maxlength="30"></label></div>@if(d.custom){<label>Your custom requirements<textarea formControlName="requirements" rows="5" maxlength="8000" placeholder="Describe the workflow or additional features you need."></textarea></label>}@if(submitted()&&form.invalid){<p class="field-error">Complete the required details and enter a six-digit PIN code.</p>}<button class="btn btn-primary" type="submit" [disabled]="busy()">{{busy()?'Preparing…':d.custom?'Submit custom request':'Review final quote'}} →</button></form></section><aside class="summary-panel"><span class="eyebrow">YOUR CONFIGURATION</span><h2>{{price()?.packageName||'Your software'}}</h2><div class="summary-lines">@for(line of price()?.lines||[];track line.code){<div><span>{{line.name}}</span><strong>{{money(line.amount)}}</strong></div>}</div><div class="summary-total"><span>{{d.custom?'Known subtotal':'Subtotal before tax'}}</span><strong>{{money(price()?.subtotal)}}</strong></div>@if(d.custom){<p class="summary-note">We’ll price the custom work after reviewing your request. No order is placed until you accept that quote.</p>}<a class="back-link" [routerLink]="['/configure',d.packageId]">← Edit features</a></aside></div>
}@else{<section class="empty-panel"><h2>Start with a software package.</h2><p>Your selected features will appear here for review.</p><a class="btn btn-primary" routerLink="/">Explore software →</a></section>}
</div>`})
export class CheckoutComponent{
 readonly draft=inject(DraftService);private api=inject(ApiService);private fb=inject(FormBuilder);private route=inject(ActivatedRoute);private router=inject(Router);
 quote=signal<Quote|null>(null);price=signal<Price|null>(null);error=signal('');busy=signal(false);accepted=signal(false);submitted=signal(false);success=signal(false);money=money;
 form=this.fb.nonNullable.group({businessName:['',[Validators.required,Validators.minLength(2)]],address:['',[Validators.required,Validators.minLength(5)]],city:['',Validators.required],state:['',Validators.required],postalCode:['',[Validators.required,Validators.pattern(/^\d{6}$/)]],taxId:[''],requirements:['']});
 constructor(){if(this.draft.value()?.custom)this.form.controls.requirements.setValidators([Validators.required,Validators.minLength(10)]);void this.load()}
 expiry(v:string){return new Date(v).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}
 async load(){try{const q=this.route.snapshot.queryParamMap.get('quote');if(q){this.quote.set(await this.api.get<Quote>('quotes/'+q));return}const d=this.draft.value();if(d){this.price.set(await this.api.post<Price>('estimates',d));const b=await this.api.get<{billing:Billing|null}>('billing-profile');if(b.billing)this.form.patchValue({...b.billing,taxId:b.billing.taxId??''})}}catch(e){this.error.set((e as Error).message)}}
 async review(){this.submitted.set(true);if(this.form.invalid||this.busy())return;this.busy.set(true);this.error.set('');try{const d=this.draft.value()!;const v=this.form.getRawValue();const billing={businessName:v.businessName,address:v.address,city:v.city,state:v.state,postalCode:v.postalCode,taxId:v.taxId};if(d.custom){await this.api.post('custom-requests',{selection:d,billing,requirements:v.requirements});this.draft.clear();this.success.set(true)}else{const q=await this.api.post<Quote>('quotes',{selection:d,billing});this.quote.set(q);await this.router.navigate([],{relativeTo:this.route,queryParams:{quote:q.id},replaceUrl:true});window.scrollTo({top:0,behavior:'smooth'})}}catch(e){this.error.set((e as Error).message)}finally{this.busy.set(false)}}
 async place(){const q=this.quote();if(!q||!this.accepted()||this.busy())return;this.busy.set(true);this.error.set('');const keyName='knightcore.order.'+q.id+'.'+q.version;let key=sessionStorage.getItem(keyName);if(!key){key=crypto.randomUUID();sessionStorage.setItem(keyName,key)}try{const r=await this.api.post<{orderId:string}>('orders',{quoteId:q.id,quoteVersion:q.version,acceptedTermsVersion:q.snapshot.termsVersion},{'Idempotency-Key':key});this.draft.clear();await this.router.navigate(['/orders',r.orderId])}catch(e){this.error.set((e as Error).message)}finally{this.busy.set(false)}}
 async edit(){this.quote.set(null);this.accepted.set(false);await this.router.navigate([],{relativeTo:this.route,queryParams:{},replaceUrl:true});await this.load()}
}

