import {Component,inject,signal,OnDestroy} from '@angular/core';
import {RouterLink,ActivatedRoute} from '@angular/router';
import {ApiService} from '../core/api.service';
import {AuthService} from '../core/auth.service';
import {OrderDetail,money,date,statusLabel} from '../core/models';
@Component({standalone:true,imports:[RouterLink],template:`
<div class="page"><a [routerLink]="auth.isAdmin?'/admin':'/workspace'" class="back-link">← Back to workspace</a>@if(error()){<div class="alert error" role="alert">{{error()}}</div>}@if(order();as o){<div class="page-heading"><div><div class="eyebrow">{{o.number}}</div><h1>{{o.snapshot.packageName}}</h1><p>Confirmed on {{date(o.createdUtc)}} · Estimated delivery {{o.snapshot.delivery}}</p></div><span class="status-badge large" [attr.data-status]="o.status">{{statusLabel(o.status)}}</span></div><div class="config-layout"><div><section class="panel"><div class="section-heading"><span class="step-circle">↗</span><div><h2>Your project, in motion.</h2><p>Follow each step from confirmation to delivery.</p></div></div><ol class="timeline">@for(h of o.history;track $index){<li><span class="timeline-dot"></span><div><strong>{{statusLabel(h.status)}}</strong><small>{{date(h.createdUtc)}}</small><p>{{h.note}}</p></div></li>}</ol>@if(o.deliveryUrl){<a class="btn btn-primary" [href]="o.deliveryUrl" target="_blank" rel="noopener">Open delivered project ↗</a>}</section><section class="panel"><h2>What’s included</h2><div class="included-grid">@for(f of o.snapshot.included;track f){<div class="included-item"><span class="check-disc">✓</span>{{f}}</div>}</div>@for(l of o.snapshot.lines.slice(1);track l.code){<div class="scope-line"><strong>{{l.name}}@if(l.quantity>1){ × {{l.quantity}}}</strong><p>{{l.description}}</p></div>}</section>
@if(auth.isAdmin&&o.allowedStatuses.length){<section class="panel"><h2>Update project status</h2><label>Next status<select #status>@for(s of o.allowedStatuses;track s){<option [value]="s">{{statusLabel(s)}}</option>}</select></label><label>Progress note<textarea #note rows="2" maxlength="1000"></textarea></label><label>Delivery URL <span class="optional">optional</span><input #delivery type="url" placeholder="https://"></label><button class="btn btn-primary" (click)="update(status.value,note.value,delivery.value)" [disabled]="busy()">Save update</button></section>}
</div><aside class="summary-panel"><span class="eyebrow">PROJECT INVOICE</span><h2>{{o.invoice.number}}</h2><div class="summary-lines">@for(l of o.snapshot.lines;track l.code){<div><span>{{l.name}}</span><strong>{{money(l.amount)}}</strong></div>}<div><span>Tax</span><strong>{{money(o.snapshot.taxAmount)}}</strong></div></div><div class="summary-total"><span>Total amount</span><strong>{{money(o.snapshot.total)}}</strong></div><p class="field-hint">Due {{date(o.invoice.dueUtc)}} · Invoice is not a payment receipt.</p><button class="btn btn-primary full-width" (click)="download()" [disabled]="busy()||o.invoice.pdfStatus!=='Ready'">{{o.invoice.pdfStatus==='Ready'?'Download invoice ↓':o.invoice.pdfStatus==='FailedNeedsAttention'?'Invoice needs attention':'Preparing invoice…'}}</button>@if(o.snapshot.evaluation){<p class="summary-footnote">Sample invoice for an evaluation order.</p>}<div class="detail-divider"></div><span class="eyebrow">BILL TO</span><h3>{{o.snapshot.billing.businessName}}</h3><p class="address">{{o.snapshot.billing.address}}<br>{{o.snapshot.billing.city}}, {{o.snapshot.billing.state}} {{o.snapshot.billing.postalCode}}</p></aside></div>}@else{<div class="loading-state"><span class="spinner"></span>Loading your project…</div>}</div>`})
export class OrderComponent implements OnDestroy{
 private api=inject(ApiService);private route=inject(ActivatedRoute);readonly auth=inject(AuthService);order=signal<OrderDetail|null>(null);error=signal('');busy=signal(false);money=money;date=date;statusLabel=statusLabel;private timer:ReturnType<typeof setTimeout>|undefined;private polls=0;
 constructor(){void this.load()}
 async load(){try{const o=await this.api.get<OrderDetail>('orders/'+this.route.snapshot.paramMap.get('id'));this.order.set(o);if(o.invoice.pdfStatus==='Pending'&&this.polls++<30)this.timer=setTimeout(()=>void this.load(),2000)}catch(e){this.error.set((e as Error).message)}}
 async download(){const o=this.order()!;this.busy.set(true);try{await this.api.download(o.invoice.id,o.invoice.number)}catch{this.error.set('Could not download the invoice. Please try again.')}finally{this.busy.set(false)}}
 async update(status:string,note:string,deliveryUrl:string){const o=this.order()!;this.busy.set(true);try{await this.api.patch('admin/orders/'+o.id+'/status',{status,note,deliveryUrl,concurrencyToken:o.concurrencyToken});await this.load()}catch(e){this.error.set((e as Error).message)}finally{this.busy.set(false)}}
 ngOnDestroy(){clearTimeout(this.timer)}
}

